### ISSUE TITLE
feat: Add testing module for Appbar Componenrt

### ISSUE THREAD

**Issue by ManonPolle** [Decathlon/vitamin-compose#172]
**Context**
Now that we have done a testing module on VitaminTextInput component, we can do the same for other components. 

**TODO** 
For Appbar component: 
- [ ] Move app bar implementation into `:appbars:appbars`
- [ ] Create testing module into `:appbars:appbars-test`. Add filters and assertions for appbars components unit tests.
- [ ] If needed, create module `:appbars:appbars-test-semantics` with new semantic
- [ ] Add Unit tests for the component into  `:appbars:appbars.test`
