### ISSUE TITLE
feat: add new icons

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-compose#47]
We need to add new icons:
- [ ] [add-circle-fill](https://github.com/Decathlon/vitamin-design/issues/58)
- [ ] [add-circle-line](https://github.com/Decathlon/vitamin-design/issues/58)
- [ ] [barcode-fill](https://github.com/Decathlon/vitamin-design/issues/43) 
- [ ] [barcode-line](https://github.com/Decathlon/vitamin-design/issues/43) 
- [ ] [customer-service-fill](https://github.com/Decathlon/vitamin-design/issues/48)
- [ ] [customer-service-line](https://github.com/Decathlon/vitamin-design/issues/48)
- [ ] [file-copy-fill](https://github.com/Decathlon/vitamin-design/issues/23)
- [ ] [file-copy-line](https://github.com/Decathlon/vitamin-design/issues/23)
- [ ] [kakao-talk-line](https://github.com/Decathlon/vitamin-design/issues/99)
- [ ] [kakao-talk-fill](https://github.com/Decathlon/vitamin-design/issues/99)
- [ ] [github-fill](https://github.com/Decathlon/vitamin-design/issues/39) 
- [ ] [github-line](https://github.com/Decathlon/vitamin-design/issues/39) 
- [ ] [line-line](https://github.com/Decathlon/vitamin-design/issues/99)
- [ ] [line-fill](https://github.com/Decathlon/vitamin-design/issues/99)
- [ ] [naver-line](https://github.com/Decathlon/vitamin-design/issues/99)
- [ ] [naver-fill](https://github.com/Decathlon/vitamin-design/issues/99)
- [ ] pie-chart-fill
- [ ] pie-chart-line
- [ ] [qr-scan-fill](https://github.com/Decathlon/vitamin-design/issues/37)
- [ ] [qr-scan-line](https://github.com/Decathlon/vitamin-design/issues/37)
- [ ] [rocket-line](https://github.com/Decathlon/vitamin-design/issues/102)
- [ ] [rocket-fill](https://github.com/Decathlon/vitamin-design/issues/102)
- [ ] [search-fill](https://github.com/Decathlon/vitamin-design/issues/57) (design update)
- [ ] [share-android-fill](https://github.com/Decathlon/vitamin-design/issues/96)
- [ ] [share-android-line](https://github.com/Decathlon/vitamin-design/issues/96)
- [ ] [share-ios-fill](https://github.com/Decathlon/vitamin-design/issues/96)
- [ ] [share-ios-line](https://github.com/Decathlon/vitamin-design/issues/96)

Thanks!

**Comment by CorentinStamperDecathlon** [comment]
We use vitamin-android icons : https://github.com/Decathlon/vitamin-android/issues/142

**Comment by lauthieb** [comment]
@CorentinStamperDecathlon okay, thanks! So I close this issue :)
